name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:assignment4-buildroot
        runs-on: ubuntu-latest
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
                URL: ${{ secrets.URL }}
                USER: ${{ secrets.USER }}
                PASS: ${{ secrets.PASS }}
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
