name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:assignment4-buildroot
        runs-on: ubuntu-latest
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: -----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABB+1NkTu5RP6Z/FPYSb/zU9AAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIEE/MEaoMwQO9AmJKo8e+htiae7Jp72lXQdqq0iS82gEAAAAoOjdlSCX7+MkvzLV7wSXP7Up8YS0/UJFm0BVvJ2wNjgbSi2aVAhqj3C2ziMQYeo4IQ06sPah2TMx7Nb10q4FYNlJB4LK4r6WbXk4s7amXq0pcOPd1CEludIM++POAni4rsRBrHoBdqSE4+xv30kmXqtKcMgtGbNEj2Wss0zB2jgbjbAq/vBKGlkfpLDoqvnfsqwDdB1VK78yFZWtrihkeQ4=-----END OPENSSH PRIVATE KEY----- 

          - name: Run full test
            env:
                GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
